Aggiunto modulo team
RainTonic/controllo_ore_x pull request #13
Opened 2023-10-02 13:01 UTC by Riccardo014

@Mochitto 

### Aggiunto 
- Aggiunto modulo di gestione del team lato front-end.

2023-10-02 15:23 UTC, Mochitto reviewed
WIP 53/162 files reviewed

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.scss
class selectors do not need to be nested to function properly.
If you want to express hierarchy, you should use BEM nomenclature.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +  implements SubscriptionsLifecycle
```suggestion
  implements SubscriptionsLifecycle, OnDestroy, OnInit
```
Better to have explicit interfaces

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +    if (!this.isCreating) {
Add comment on why this should be done if the user is not creating

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +    return this._teamDataService.getOne(this.userId).subscribe((user: any) => {
```suggestion
    return this._teamDataService.getOne(this.userId).subscribe((user: UserReadDto) => {
```
No idea if the type is that one, but you should know the type of user; don't use any

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +   * Get users' roles from database.
```suggestion
   * Fetch and set the users' roles from the database.
   ```

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +  private _getUser(): Subscription {
Add docstring

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +    super.onSubmit();
If you are calling the supers's method, name this one a different way; if you overwrite the docstring will be inherited I think, which would be wrong for the child class.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +  togglePassword(): boolean | null {
```suggestion
  togglePasswordVisibility(): void {
```
Don't make this return anything (it doesn't make sense) and don't assign values in ternary operators.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/helpers/team.form-helper.ts
> +  setCreationMode(): void {
Add docstring

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/helpers/team.form-helper.ts
> +  patchForm(value: UserReadDto): boolean {
Don't assume the operation is successful by returning true; makes the return value useless.
If the method doesn't throw errors then use `form.valid` to decide the return value or if to throw an error.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +export class TeamIndexPage extends IndexPage<
add Subscription lifecycle and remove the $destroy

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +    this.isLoading.pipe(takeUntil(this.destroy$)).subscribe((r) => {
```suggestion
    this.isLoading.pipe(takeUntil(this.destroy$)).subscribe((isLoading) => {
```
These might be not needed with the fixes to the parent class, since you set the loading in the init and have the subscriptions happening there.

This probably triggers the parent's method multiple time.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +    this.isFirstLoadDone.pipe(takeUntil(this.destroy$)).subscribe((r) => {
```suggestion
    this.isFirstLoadDone.pipe(takeUntil(this.destroy$)).subscribe((isFirstLoadDone) => {
```
These might be not needed with the fixes to the parent class, since you set the loading in the init and have the subscriptions happening there.

This probably triggers the parent's method multiple time.

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +    console.log('openConfirmationDelete', user);
remove console log

2023-10-02 15:23 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +  openDialogFn($event: any): void {
don't use any

2023-10-03 06:47 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +   * @param user
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/acf42af5eddc0d02af225d291ca0a0c2b9f8742b

2023-10-03 06:47 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +   * @param user
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/acf42af5eddc0d02af225d291ca0a0c2b9f8742b

2023-10-03 06:48 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +  static async userRoleIsCollaboratorOrHigher(
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/acf42af5eddc0d02af225d291ca0a0c2b9f8742b

2023-10-03 06:48 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +  static async userRoleIsAdminOrHigher(
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/acf42af5eddc0d02af225d291ca0a0c2b9f8742b

2023-10-03 06:48 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +   * @param user
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/dd11d474d2e0b1c464efbf1388266cb5882a84a0

2023-10-03 06:49 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +  static async checkPermission(
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/1fe7f2ff21fb397747dc973064edf33626a87927

2023-10-03 06:53 UTC, Riccardo014 commented on apps/api/src/app/modules/index-configuration/index-configuration.module.ts
> +      this.seedData();
I didn't changed it because, i have this error: `'await' expressions are only allowed within async functions and at the top levels of modules.`, so i keeped the seedData function

2023-10-03 06:53 UTC, Riccardo014 commented on apps/api/src/app/modules/index-configuration/index-configuration.module.ts
> +  async seedData(): Promise<void> {
same as the previous comment

2023-10-03 06:57 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_core/services/role-data.service.ts
> +export class RoleDataService extends DataService<
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/96d5893039192f515e4a095d9857c83b660ca10a

2023-10-03 07:05 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_core/interceptors/auth.interceptor.ts
> +  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
The retutn type of the handle function is Observable<HttpEvent<any>>, and the request type, (also as a param of the handle function) is HttpRequest<any>.
I didn't find any best ways

2023-10-03 07:15 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +   * @param value
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/dd8e20b2214a2d6cf053fbe187d398bd141db087

2023-10-03 07:15 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +   * Returns the form to be used in _form
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/dd8e20b2214a2d6cf053fbe187d398bd141db087

2023-10-03 07:16 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +   * It gets form valid value
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/dd8e20b2214a2d6cf053fbe187d398bd141db087 i removed the method

2023-10-03 07:16 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +   * It gets form invalid value
I removed the valid function: https://github.com/RainTonic/controllo_ore_x/pull/13/commits/dd8e20b2214a2d6cf053fbe187d398bd141db087

2023-10-03 08:58 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +export abstract class FormHelper<T> {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/bdc1a1d7600b77e4a4402211d91b6c9c36027fed

2023-10-03 09:01 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/form-helper.class.ts
> +   * Returns boolean value if patch is done successfully
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/f304f5aae910eab7f5320726b98e64496b19aa9f

2023-10-03 09:02 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-form-helper.class.ts
> + * Class that handles a form and implements create, update, delete and basic get functions
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/764ee6c706e246f42c1318dd722d430e697cbf49

2023-10-03 09:03 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-form-helper.class.ts
> +   * ID of the current entity in case of update.
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/764ee6c706e246f42c1318dd722d430e697cbf49

2023-10-03 09:03 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-form-helper.class.ts
> +   * Value that stores the current entity in case of update. It is used to patch the form initially.
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/764ee6c706e246f42c1318dd722d430e697cbf49

2023-10-03 09:05 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +  async init(): Promise<void> {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:05 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +    } catch (e) {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:05 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * @param tab
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:05 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * Change the current tab if the page has tabs
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:06 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +  changeTab(tab: number): void {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:06 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +  getResourceId(): string {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:06 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +    if (this.formHelper.invalid) {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:06 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +export abstract class UpsertPage<T extends { _id: string }, CreateT, UpdateT>
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:06 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +    } catch (error) {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:07 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * It handles the create function onSubmit
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:07 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * @protected
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:08 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +      return;
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:08 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * Returns the actual resource id
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:08 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * It handles the update function onSubmit
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:08 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +  protected async onCreate(): Promise<void> {
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 09:09 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * Method to attach on "Save" button
https://github.com/RainTonic/controllo_ore_x/pull/13/commits/785e72f5a4bff8b225c4719860e5438e89b353e7

2023-10-03 10:18 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/components/index-template/index-template.component.ts
> +  private _setLoadingParameters(): void {
Review logic

2023-10-03 11:00 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/dialogs/team-upsert/team-upsert.page.ts
> +    return this._teamDataService.getOne(this.userId).subscribe((user: any) => {
The type is a UserReadDto but it also has the `role` nested, so i put any

2023-10-03 12:20 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +export class TeamIndexPage extends IndexPage<
i removed the subscriptions

2023-10-03 12:21 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +    this.isLoading.pipe(takeUntil(this.destroy$)).subscribe((r) => {
i removed the subscriptions

2023-10-03 12:21 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/modules/auth/modules/team/pages/team-index.page.ts
> +    this.isFirstLoadDone.pipe(takeUntil(this.destroy$)).subscribe((r) => {
i removed the subscriptions

2023-10-03 13:08 UTC, Mochitto requested changes

2023-10-03 13:08 UTC, Mochitto commented on libs/ui/core/partials-consts/partial-table-consts.scss
You should split consts either between components or group.
If you decide to split depending on group (meaning of the const) then you should divide them between layout, theme and typography.

2023-10-03 13:55 UTC, Riccardo014 commented on libs/api-interfaces/src/interfaces/table-configuration.interface.ts
> +  type: 'NUMBER' | 'STRING' | 'DATE' | 'TIME_DATE' | 'BOOLEAN' | 'EDITABLE' | string;
I think that the string is there as a "default" value

2023-10-03 15:11 UTC, Riccardo014 commented on libs/rt-shared/src/alert/services/alert.service.ts
> +  openSuccess(title: string = 'Ottimo!', text: string = 'Procedura completata con successo.', details?: any): void {
`details` should be any since it is an error in a catch

2023-10-04 07:04 UTC, Riccardo014 commented on libs/rt-shared/src/rt-dialog/interfaces/i-rt-dialog-close.interface.ts
> +export interface IRtDialogClose<T = any> {
For me it's not possible to remove it

2023-10-04 07:06 UTC, Riccardo014 commented on libs/rt-shared/src/rt-dialog/interfaces/i-rt-dialog-input.interface.ts
> +export interface IRtDialogInput<T = any> {
For me it's not possible to remove it

2023-10-04 07:15 UTC, Riccardo014 commented on libs/rt-shared/src/rt-dialog/services/rt-dialog.service.ts
> +    // put data inside input to be conform with TInput interface
the comment is not true, i've removed it

2023-10-04 08:37 UTC, Riccardo014 commented on libs/rt-shared/src/rt-select/shared/class/select-control-value-accessor-connector.ts
> +  override set compareWith(fn: (o1: any, o2: any) => boolean) {
i can't change the names in the base class, since this method are of  SelectControlValueAccessor that is an angular class

2023-10-04 08:38 UTC, Riccardo014 commented on libs/rt-shared/src/rt-select/shared/class/select-control-value-accessor-connector.ts
> +  override get compareWith() {
i can't change the names in the base class, since this method are of SelectControlValueAccessor that is an angular class

2023-10-04 08:41 UTC, Riccardo014 commented on libs/rt-shared/src/rt-select/shared/class/select-control-value-accessor-connector.ts
> +    this.formControlDirective.valueAccessor?.registerOnChange(fn);
I removed it

2023-10-04 08:42 UTC, Riccardo014 commented on libs/rt-shared/src/rt-select/shared/class/select-control-value-accessor-connector.ts
> +    this.formControlDirective.valueAccessor?.writeValue(obj);
I removed it

2023-10-04 09:26 UTC, Riccardo014 commented on libs/rt-shared/src/rt-table/components/rt-filter/rt-filter.component.ts
I taked it from manaly, maybe, when i'll have to use filters, i'll look at the genos' one and check if it is better for my use case

2023-10-04 10:08 UTC, Riccardo014 commented on libs/rt-shared/src/rt-dialog/services/rt-dialog.service.ts
> +  open<TInput = any, TReturn = any>(
it seems to be an unused method

2023-10-04 10:25 UTC, Riccardo014 commented on libs/rt-shared/src/rt-table/components/rt-table/rt-table.component.ts
> +  @Input() data!: any[];
the data type should be every entityReadDto, so i keeped any

2023-10-04 10:39 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/index-page.class.ts
> +  configuration!: TableConfiguration;
i checked it in the constructor

2023-10-19 12:53 UTC, merged