Menu and logout
RainTonic/controllo_ore_x pull request #14
Opened 2023-10-19 13:34 UTC by Riccardo014

### Aggiunto

- Aggiunta funzionalità di logout.
- Aggiunto menù dell'applicazione.

2023-10-19 14:10 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +    //* this condition is to avoid multiple active voices on sidebar
Review together

2023-10-20 07:16 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +  MAIN_MENU: IMainMenuVoice[] = MAIN_MENU;
I prefer to have them separate because they are accessible only by specific roles

2023-10-20 07:38 UTC, Mochitto requested changes

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
>    MAIN_MENU_SECTIONS: IMenuSections[] = MAIN_MENU_SECTIONS;
Turn the MENU_SECTIONS into an array so that you will be able to easily add more menus in the future (and change their order); use a for loop in the html to build the sections

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/components/sidenav-section/sidenav-section.component.ts
> +        this.selectedSection = this._router.url.split('/')[2];
Make this an input; you should keep the active section fetching logic outside of the component

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +  routerLink?: string;
```suggestion
  routerLink: string;
```
This is found in all the current menus

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +export interface IMenuSections {
Add docstring both to the interface and to the properties.
Docstrings to properties are added by making a docstring on top of the property.
```
interface hello {
/** This is the property docstring*/
property: something
}
```

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +      this._router.events.subscribe(() => {
Extract this to a function `updateActiveSectionOnRouterEvent` and add docstring.

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +        this.selectedSection = this._router.url.split('/')[2];
```suggestion
        this.selectedSection = this.getActiveSectionFromUrl(this._router_url)
```

Extracting this into its own function makes it possible to maintain only that specific function in the future without having to break this subscription. as of now the function will just be `return url.split(etc.)`, but in the future it could become more complex and having it in a special function also creates a good ground for that.

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +  selectedSection: string;
```suggestion
  activeSection: string;
```
Change also CSS classes to `active`; it better represents the UX and HTML (the elements are `li`, not radio buttons or other inputs that can be selected and deselected.

2023-10-20 07:38 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
>        this._sidenavService.visibiliyObservable.subscribe(
Extract  this into `keepSidenavVisibilityInSync`

2023-10-20 07:43 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
>    MAIN_MENU_SECTIONS: IMenuSections[] = MAIN_MENU_SECTIONS;
Can ignore this comment

2023-10-20 08:37 UTC, Mochitto requested changes

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> + * Interface for menu sections
```suggestion
 * A configuration object that describes a nav-bar section.
```

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +   * Label for menu section
```suggestion
   * The label linked to the menu section.
```

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +   * The router link for menu section
```suggestion
   * The route that should be linked to this specific menu section. 
   * 
   * @example
   * Component: `Contacts.page.ts` =>
   * Route at which the component is mounted: ` /contacts` =>
   * This property: `contacts`
```

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +export interface IMenuSections {
```suggestion
export interface IMenuSection {
```
Ho notato ora che era al plurale

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/interfaces/i-menu-sections.interface.ts
> +   * The icon for menu section
```suggestion
   * The icon for menu section. Should be a mat-icon.
```

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/components/sidenav-section/sidenav-section.component.ts
> +  @Input() MENU_SECTIONS!: IMenuSections[];
Add guards in the ngOnInit to check for these properties to be set, when using `!`.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

Check for properties that are in IMenuSections to validate the input.
For the activeSection, check that it's a string and, if you want, that `location.url` includes it.

Throw descriptive errors if any of these fail.

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +   * Update the active section on router event on router changes
```suggestion
   * Update the active section on route changes.
```

2023-10-20 08:37 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.ts
> +    return this._router.events.subscribe(() => {
You can check if the event is a `navigationStart` event before running the function.
https://angular.io/api/router/RouterEvent
(not sure it's a navigation start; you should console log to make sure)

2023-10-20 08:41 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/components/sidenav-section/sidenav-section.component.ts
> +  @Input() MENU_SECTIONS!: IMenuSections[];
Basically define two guards `areMenuSectionsValid` and `isActiveSectionValid` and in the ngOnInit do
```
if property is not valid => throw error
```

2023-10-20 10:27 UTC, Mochitto commented
Merged with commit: 11bb284

2023-10-20 10:27 UTC, closed without merging