Moduli progetti e release
RainTonic/controllo_ore_x pull request #16
Opened 2023-10-23 08:36 UTC by Riccardo014

@Mochitto 
### Features Aggiunte

- +Aggiunto modulo di gestione dei progetti.
- +Aggiunto modulo di gestione delle release.

2023-10-23 15:27 UTC, Mochitto requested changes
WIP 38/103

2023-10-23 15:27 UTC, Mochitto commented on apps/api/src/app/modules/project/services/project.service.ts
>        const releaseData = {
extract to `formatReleaseCreateData(project: Project): ProjectCreateDto`

```suggestion
      const releaseCreateData = formatReleaseCreateData(project);
```

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_core/services/customer-data.service.ts
filename should be customer.data-service.ts

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/base-dialog.class.ts
> +  navigateAfterDelete(): void {
Add docstring and consider changing name. The function name shouldn't be where in the app's flow it's used; since the delete doesn't happen in the function, it shouldn't be part of the method's name.

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/base-dialog.class.ts
>                await this.formHelper.delete();
at L53 change r => result: RT_DIALOG_CLOSE_RESULT

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/base-dialog.class.ts
>              } catch (err) {
Log the error with `console.error`

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/index-page.class.ts
> +  isPageWithTable: boolean = true;
Add docstrings to these flag properties to better explain their use.

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/index-page.class.ts
>    subscriptionsList: Subscription[] = [];
Divide the properties in groups: [subscriptionList], [flags], [configuration, indexTableHandler]. Basically divide them with whitelines for readability.

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-form-helper.class.ts
> +        next: (res: any) => {
```suggestion
        next: (res: ReadT) => {
```
You should be able to use the generics passed to the class I think

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/classes/upsert-page.class.ts
> +   * Perform a create or update operation depending on the `isCreating` flag.
instead of one flag for creating, create a `transactionStatus: 'create' | 'update'`; use a switch statement instead of a ternary for readability and throw an error in the default case, since we shouldn't reach it.

You can use a different name if you have better ideas.

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/index-template/index-template.component.scss
> +  // padding-bottom: 40px;
remove commented out code

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/_shared/components/sidenav/sidenav.component.scss
> +  height: calc(100vh - 81px);
81px is a magic number. Consider moving it to a variable and setting things using the variable; this is very hard to maintain if the 81 becomes another number.
Likely used in other SCSS files; make sure all of them are fixed. (we had problems with this on calzedonia)

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/customer/helpers/customer.form-helper.ts
>      return formValues;
```suggestion
    return this.form.getRawValue();
```

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/customer/helpers/customer.form-helper.ts
>      return formValues;
```suggestion
    return this.form.getRawValue();
```

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/components/project-release-table-line/project-release-table-line.component.ts
> +  @Input() release!: ReleaseReadDto;
Validate input since it has `!` with a guard

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/components/project-release-table-line/project-release-table-line.component.ts
> +      this._userHoursDataService
extract into `sethoursExecutedProperty`

2023-10-23 15:27 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/components/project-release-table-line/project-release-table-line.component.ts
> +  convertNumberToHours(number: number): string {
use a better var name instead of number; number doesn't tell you what the data represents

2023-10-24 06:54 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_core/services/customer-data.service.ts
file deleted

2023-10-24 06:59 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/base-dialog.class.ts
>                await this.formHelper.delete();
i changed it in this way: r => closeResult: IRtDialogClose

2023-10-24 07:46 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/_shared/classes/base-dialog.class.ts
> +  navigateAfterDelete(): void {
i changed to `navigationDestination` but i don't really like it

2023-10-24 09:20 UTC, Mochitto requested changes
Ignore comments on renaming overrided var names.

WIP 63/102

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-header/release-table-header.component.scss
> +  &__datas {
```suggestion
  &__information {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +    &--crossed-out {
```suggestion
    &--completed {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +      &--date {
```suggestion
      &__date {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +      &--progress {
```suggestion
      &__progress {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +      &--edit {
Can be removed if no style is applied; can directly be `options__icon`

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +      &--report {
```suggestion
      &__report {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +        &__elements {
Use a more descriptive name

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.scss
> +    &__element {
Use a more descriptive name

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.ts
> +  @Input() release!: ReleaseReadDto;
Add validator\type guard in `ngOnInit`

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.ts
> +  convertNumberToHours(number: number): string {
Move to an util file.
Add docstring.
Change param name to something more descriptive.

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.ts
> +    this.deadline = new Date(deadline).toLocaleDateString();
use intl library instead of toLocaleDateString.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.ts
> +      .subscribe();
add to sub lifecycle

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table-line/release-table-line.component.ts
> +  openReport($event: ReleaseReadDto): void {
```suggestion
  openReportDialog($event: ReleaseReadDto): void {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table/release-table.component.ts
> +  @Input() projectId!: string;
Add type guard and validator in `ngOnInit`

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/components/release-table/release-table.component.ts
> +  _getReleases(): Subscription {
```suggestion
  _fetchSetReleases(): Subscription {
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/dialogs/release-dialog/release.dialog.html
> +              *ngIf="formHelper.form.controls['billableHoursBudget'].hasError(error.name)"
Make a function to unwrap the error name
```suggestion
              *ngIf="getFormControlError('billableHoursBudget')"
```

2023-10-24 09:20 UTC, Mochitto commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/modules/release/dialogs/release-dialog/release.dialog.ts
> +  override isCreating: boolean = true;
Use componentStatus instead

2023-10-24 10:26 UTC, Riccardo014 commented on apps/controllo-ore-x/src/app/modules/auth/modules/project/dialogs/project-dialog/project.dialog.ts
> +          this.currentCustomer = this.customers.find(
It's just for fill the form on the edit/duplicate mode

2023-10-27 14:32 UTC, merged