Initial configuration and created entities user/role
RainTonic/controllo_ore_x pull request #2
Opened 2023-09-14 06:59 UTC by Riccardo014

- Configurazione del progetto con nx, nest e angular
- aggiunta libreria UI
- aggiunto generatore
- abilitati middleware
- aggiunto CrudService
- aggiunto ServeStatic
- aggiunto find-boosted
- aggiunto role
- aggiunto user

2023-09-15 09:10 UTC, RTsosssoldi requested changes
Non ho fatto la review dei file FE perchè non so in che stato sono e soprattutto non ne ho il tempo ora.
Per il BE, la cosa più grossa da gestire ASAP sono le guardie, ti faccio un request changes dai un occhio ai commenti

2023-09-15 09:10 UTC, RTsosssoldi commented on apps/api/src/app/modules/user/seeds/role.seed.ts
> +    name: 'Collaborator',
Collaboratore, i testi visibili mettiamoli in ita

2023-09-15 11:05 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/role-create.dtov.ts
> +  @IsOptional() @IsString() permissions: string;
- commento: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/c3377c15692dde1f5994ffe017128fc2218edd5b
- refactoring: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/401556a8ed708cba853de4fbb8981d4256bc7fb4

2023-09-15 11:06 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/role-update.dtov.ts
> +  @IsOptional() @IsString() permissions?: string;
https://github.com/RainTonic/controllo_ore_x/pull/2/commits/07bdaa388b5d44d8d6a1c96c4c699dda09bdfa28

2023-09-15 11:08 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/user-create.dtov.ts
> +  @IsString() email: string;
https://github.com/RainTonic/controllo_ore_x/pull/2/commits/5c6f953ab8134680cfb8491ac1dacabef0f81a16

2023-09-15 11:10 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/user-create.dtov.ts
> +  @IsString() roleId: string;
- decorator: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/5c6f953ab8134680cfb8491ac1dacabef0f81a16
- rimozione vecchio decorator: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/a916cb8726fd1805a5c6ece10cdb4c16efd96750

2023-09-15 11:12 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/user-update.dtov.ts
> +  @IsOptional() @IsString() roleId?: string;
- decorator: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/7e9771f1f72b274f370cc29557e08424ea476436
- rimozione vecchio decorator: https://github.com/RainTonic/controllo_ore_x/commit/a916cb8726fd1805a5c6ece10cdb4c16efd96750

2023-09-15 11:13 UTC, Riccardo014 commented on apps/api/src/app/modules/user/seeds/role.seed.ts
> +    name: 'Collaborator',
https://github.com/RainTonic/controllo_ore_x/pull/2/commits/73783e6dd790db0bdf65a9ed0b7ef4bd241352c6

2023-09-15 15:10 UTC, RTsosssoldi requested changes

2023-09-15 15:10 UTC, RTsosssoldi commented on apps/api/src/app/modules/user/dtov/role-create.dtov.ts
> +  @IsOptional()
Non avevo visto questo, togli isoptional

2023-09-15 15:28 UTC, Riccardo014 commented on apps/api/src/app/modules/user/dtov/role-create.dtov.ts
> +  @IsOptional()
https://github.com/RainTonic/controllo_ore_x/pull/2/commits/a11b6de22445af3264353c03fcadd53d9b3abfcf

2023-09-18 07:28 UTC, Riccardo014 commented on apps/api/src/app/modules/user/controllers/role.controller.ts
> +import { Body, Controller, Get, Param, Post, Put, Query } from '@nestjs/common';
- creato auth module https://github.com/RainTonic/controllo_ore_x/pull/2/commits/6d8d433d9688c342d43a4842d3a7bf8e5e13b918
- creata la guardia: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/1cb52159cbca6fdd753dca326032df75918aee50

2023-09-18 07:28 UTC, Riccardo014 commented on apps/api/src/app/modules/user/controllers/user.controller.ts
> +import { Body, Controller, Delete, Get, Param, Post, Put, Query } from '@nestjs/common';
- creato auth module https://github.com/RainTonic/controllo_ore_x/pull/2/commits/6d8d433d9688c342d43a4842d3a7bf8e5e13b918
- creata la guardia: https://github.com/RainTonic/controllo_ore_x/pull/2/commits/1cb52159cbca6fdd753dca326032df75918aee50

2023-09-19 07:45 UTC, RTsosssoldi requested changes
Giusto un controllo in più sul metodo dei ruoli e ci siamo!

2023-09-19 07:45 UTC, RTsosssoldi commented on apps/api/src/app/_shared/utils/role-checker.ts
> +    const currentUserRole = (await _userService.getOne( user._id, [ 'role' ] )).role;
farei un passaggio in più ai finidel debug, await il find di user, gestisci il fatto che potrebbe tornare undefined o andare in errore con un check su user. Solo dopo utilizza user.role

2023-09-19 08:23 UTC, Riccardo014 commented on apps/api/src/app/_shared/utils/role-checker.ts
> +    const currentUserRole = (await _userService.getOne( user._id, [ 'role' ] )).role;
https://github.com/RainTonic/controllo_ore_x/pull/2/commits/ba941522a3cb670d3de815a3a0bbb8c7f3050c95

2023-09-19 08:41 UTC, RTsosssoldi approved these changes

2023-09-19 09:39 UTC, merged